name: Release Build
on:
  create:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Bootstrap v86-buildroot
        run: make bootstrap

      - name: Configure Buildroot
        run: make buildroot-defconfig

      - name: Build Buildroot
        run: make all

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: build/*/images/